version: 2.1


jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Create distribution
          command: |
            printf "@tictrac:registry=https://tictrac.jfrog.io/artifactory/api/npm/npm/\nemail=developer@tictrac.com\nalways-auth=true\n_auth=$JFROG_AUTH_ENC\nhttps://registry.npmjs.org/" > ~/.npmrc
            cd packages/ckeditor5-build-balloon-block
            npm publish --registry https://tictrac.jfrog.io/artifactory/api/npm/npm/
      - slack/status

workflows:
  tictrac:
    jobs:
      - build:
          name: Docker build
          context: Infrastructure
          filters:
            tags:
              only: /^.*/
            branches:
              only: /.*/

orbs:
  slack: circleci/slack@3.4.2
